*** Settings ***
Resource  ../../Regression/A&E/TC_AE_001.robot
Resource  ../../Regression/A&E/TC_AE_002.robot
Resource  ../../Regression/A&E/TC_AE_003.robot
Resource  ../../Regression/A&E/TC_AE_004.robot
Resource  ../../Regression/A&E/TC_AE_005.robot
Resource  ../../Regression/A&E/TC_AE_006.robot
Resource  ../../Regression/A&E/TC_AE_007.robot
Resource  ../../Regression/A&E/TC_AE_008.robot
Resource  ../../Regression/A&E/TC_AE_009.robot
Resource  ../../Regression/A&E/TC_AE_010.robot
Resource  ../../Regression/A&E/TC_AE_011.robot
Resource  ../../Regression/A&E/TC_AE_012.robot
Resource  ../../Regression/A&E/TC_AE_013.robot
Resource  ../../Regression/A&E/TC_AE_014.robot
Resource  ../../Regression/A&E/TC_AE_015.robot
Resource  ../../Regression/A&E/TC_AE_016.robot
Resource  ../../Regression/A&E/TC_AE_017.robot
Resource  ../../Regression/A&E/TC_AE_018.robot
Resource  ../../Regression/A&E/TC_AE_019.robot
Resource  ../../Regression/A&E/TC_AE_020.robot
Resource  ../../Regression/A&E/TC_AE_021.robot
Resource  ../../Regression/A&E/TC_AE_022.robot
Resource  ../../Regression/A&E/TC_AE_023.robot
Resource  ../../Regression/A&E/TC_AE_024.robot
Resource  ../../Regression/A&E/TC_AE_025.robot
Resource  ../../Regression/A&E/TC_AE_026.robot
Resource  ../../Regression/A&E/TC_AE_027.robot
Resource  ../../Regression/A&E/TC_AE_028.robot
Resource  ../../Regression/A&E/TC_AE_029.robot
Resource  ../../Regression/A&E/TC_AE_030.robot
Resource  ../../Regression/A&E/TC_AE_031.robot
Resource  ../../Regression/A&E/TC_AE_032.robot
Resource  ../../Regression/A&E/TC_AE_033.robot
Resource  ../../Regression/A&E/TC_AE_034.robot
Resource  ../../Regression/A&E/TC_AE_035.robot
Resource  ../../Regression/A&E/TC_AE_036.robot
Resource  ../../Regression/A&E/TC_AE_037.robot
Resource  ../../Regression/A&E/TC_AE_038.robot
Resource  ../../Regression/A&E/TC_AE_039.robot
Resource  ../../Regression/A&E/TC_AE_040.robot
Resource  ../../Regression/A&E/TC_AE_041.robot
Resource  ../../Regression/A&E/TC_AE_042.robot
Resource  ../../Regression/A&E/TC_AE_043.robot
Resource  ../../Regression/A&E/TC_AE_044.robot
Resource  ../../Regression/A&E/TC_AE_045.robot
Resource  ../../Regression/A&E/TC_AE_046.robot
Resource  ../../Regression/A&E/TC_AE_047.robot
Resource  ../../Regression/A&E/TC_AE_048.robot
Resource  ../../Regression/A&E/TC_AE_049.robot
Resource  ../../Regression/A&E/TC_AE_050.robot
Resource  ../../Regression/A&E/TC_AE_051.robot
Resource  ../../Regression/A&E/TC_AE_052.robot
Resource  ../../Regression/A&E/TC_AE_053.robot
Resource  ../../Regression/A&E/TC_AE_054.robot
Resource  ../../Regression/A&E/TC_AE_055.robot
Resource  ../../Regression/A&E/TC_AE_056.robot
Resource  ../../Regression/A&E/TC_AE_057.robot
Resource  ../../Regression/A&E/TC_AE_058.robot
Resource  ../../Regression/A&E/TC_AE_059.robot
Resource  ../../Regression/A&E/TC_AE_060.robot
Resource  ../../Regression/A&E/TC_AE_061.robot
Resource  ../../Regression/A&E/TC_AE_062.robot
Resource  ../../Regression/A&E/TC_AE_063.robot
Resource  ../../Regression/A&E/TC_AE_064.robot
Resource  ../../Regression/A&E/TC_AE_065.robot
Resource  ../../Regression/A&E/TC_AE_066.robot
Resource  ../../Regression/A&E/TC_AE_067.robot
Resource  ../../Regression/A&E/TC_AE_068.robot
Resource  ../../Regression/A&E/TC_AE_069.robot
Resource  ../../Regression/A&E/TC_AE_070.robot
Resource  ../../Regression/A&E/TC_AE_071.robot
Resource  ../../Regression/A&E/TC_AE_072.robot
Resource  ../../Regression/A&E/TC_AE_073.robot
Resource  ../../Regression/A&E/TC_AE_074.robot
Resource  ../../Regression/A&E/TC_AE_075.robot
Resource  ../../Regression/A&E/TC_AE_076.robot
Resource  ../../Regression/A&E/TC_AE_077.robot
Resource  ../../Regression/A&E/TC_AE_078.robot
Resource  ../../Regression/A&E/TC_AE_079.robot
Resource  ../../Regression/A&E/TC_AE_080.robot
Resource  ../../Regression/A&E/TC_AE_081.robot
Resource  ../../Regression/A&E/TC_AE_082.robot
Resource  ../../Regression/A&E/TC_AE_083.robot
Resource  ../../Regression/A&E/TC_AE_084.robot
Resource  ../../Regression/A&E/TC_AE_085.robot
Resource  ../../Regression/A&E/TC_AE_086.robot
